title:              Randy Klabacka
email:              klabacka.randy@gmail.com
description:        Evolutionary Biologist
author:             Randy Klabacka
url:                "RandyKlabacka.com"

# Social Profiles
twitter_username:   r_klabacka
github_username:    rklabacka
facebook_username:  klabacka
linkedin_username:  klabacka

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
